### ISSUE TITLE
Failed

### ISSUE THREAD

**Issue by ZWH55** [tud-amr/guidance_planner#1]
example: /usr/local/include/eigen3/Eigen/src/Core/PlainObjectBase.h:273: void Eigen::PlainObjectBase<Derived>::resize(Eigen::Index, Eigen::Index) [with Derived = Eigen::Matrix<double, 2, 1>; Eigen::Index = long int]: Assertion `(!(RowsAtCompileTime!=Dynamic) || (rows==RowsAtCompileTime)) && (!(ColsAtCompileTime!=Dynamic) || (cols==ColsAtCompileTime)) && (!(RowsAtCompileTime==Dynamic && MaxRowsAtCompileTime!=Dynamic) || (rows<=MaxRowsAtCompileTime)) && (!(ColsAtCompileTime==Dynamic && MaxColsAtCompileTime!=Dynamic) || (cols<=MaxColsAtCompileTime)) && rows>=0 && cols>=0 && "Invalid sizes when resizing a matrix or array."' failed.

**Comment by oscardegroot** [comment]
Thanks for raising this issue. I could reproduce the issue and fixed it in the latest commit (the issue was in `include/guidance_planner/types/space_time_point.h`). 

If this indeed fixes the issue for you, please close it.
